#!/bin/bash

PATH=/usr/sbin:/usr/bin:/sbin:/bin

prog=$(basename $0)
exec=$(which $prog)

if [ -n "${exec}" ]; then
  exec ${exec} $@
else
  USER_UID=$(id -u)
  USER_GID=$(id -g)
  TZ=$(cat /etc/timezone)
  ( id -Gn | grep docker ) || SUDO=sudo

  # remove stopped containers
  echo "Removing stopped containers..."
  for c in $(${SUDO} docker ps -a -q)
  do
    image="$(${SUDO} docker inspect -f {{.Config.Image}} ${c})"
    if [ "${image}" == "sameersbn/skype:latest" ]; then
      running=$(${SUDO} docker inspect -f {{.State.Running}} ${c})
      if [ "${running}" != "true" ]; then
        ${SUDO} docker rm "${c}" >/dev/null
      fi
    fi
  done

  # enumerate video devices for webcam support
  VIDEO_DEVICES=
  for device in /dev/video*
  do
    if [ -c $device ]; then
      VIDEO_DEVICES="${VIDEO_DEVICES} --device $device:$device"
    fi
  done

  xhost +local:
  echo "Starting ${prog}..."
  ${SUDO} docker run -d \
    --env="USER_UID=${USER_UID}" \
    --env="USER_GID=${USER_GID}" \
    --env="DISPLAY=${DISPLAY}" \
    --env="TZ=${TZ}" \
    ${VIDEO_DEVICES} \
    --volume=${HOME}/.Skype:/home/skype/.Skype \
    --volume=${HOME}/Downloads:/home/skype/Downloads \
    --volume=/tmp/.X11-unix:/tmp/.X11-unix \
    --volume=/run/user/${USER_UID}/pulse:/run/pulse \
    sameersbn/skype:latest $(basename $0) $@ >/dev/null
fi
